import type { Metadata } from "next";
import "./globals.scss";
import React from "react";
import {ThemeProvider} from "@/src/providers/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({  children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body>
        <ThemeProvider
            defaultTheme="system"
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
